#!/usr/bin/env python3
"""Build the EL0 demo blob and regenerate Userland/UserBlob.swift.

User/demo.S is a pure position-independent aarch64 program (no libc, no
external symbols). It is assembled with clang and linked flat at address 0
with ld.lld --oformat binary; the kernel copies the image to the start of
an EL0-mapped page and enters at offset 0 (see Kernel/Userspace.swift).

Usage: python3 tools/mkblob.py
"""

import os
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "User" / "demo.S"
OUT = ROOT / "Userland" / "UserBlob.swift"
CLANG = ["xcrun", "clang", "--target=aarch64-none-elf"]
LLD = os.path.expanduser("~/.swiftly/bin/ld.lld")

# The loader maps a single 4 KiB page for the blob (Kernel/Userspace.swift).
MAX_BLOB_BYTES = 4096


def build_blob() -> bytes:
    with tempfile.TemporaryDirectory() as td:
        obj = os.path.join(td, "demo.o")
        flat = os.path.join(td, "demo.bin")
        subprocess.run(CLANG + ["-c", str(SRC), "-o", obj], check=True)
        subprocess.run(
            [LLD, "-Ttext=0", "--oformat", "binary", "-o", flat, obj],
            check=True,
        )
        with open(flat, "rb") as f:
            return f.read()


def emit_swift(data: bytes) -> str:
    lines = [
        "// EL0 demo user program, as a flat aarch64 binary.",
        "// GENERATED by tools/mkblob.py from User/demo.S — do not edit by hand;",
        "// regenerate with `python3 tools/mkblob.py`.",
        "//",
        "// Pure position-independent code linked at address 0 (no imports of",
        "// any kind — this file is a plain byte literal). The loader copies",
        "// the image to the start of an EL0-mapped page and enters at",
        "// offset 0. Syscall ABI: svc #0, number in x8 — see User/demo.S.",
        "",
        "enum UserBlob {",
        "    static let bytes: [UInt8] = [",
    ]
    for off in range(0, len(data), 12):
        chunk = data[off : off + 12]
        lines.append("        " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines += [
        "    ]",
        "}",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    data = build_blob()
    if len(data) > MAX_BLOB_BYTES:
        print(f"mkblob: blob is {len(data)} bytes, over the {MAX_BLOB_BYTES}-byte page budget",
              file=sys.stderr)
        return 1
    OUT.write_text(emit_swift(data))
    print(f"mkblob: {len(data)} bytes -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
